#define LCD_COLS 16
#define LCD_ROWS 2

#define ENC_PIN_CLK 25 
#define ENC_PIN_DT 33
#define ENC_PIN_SW 32


#define MAX_MENUS 3
#define MAX_MENU_NODES 10

#define MAX_STRING_LENGTH 20

#define UART_BAUD 115200
#define UART_TX_PIN 17

#define IO_MAX_STR_LEN 25
#define IO_LINE_SIZE 32
#define IO_MAX_SYMBOLS 10
#define MAX_PATH_LEN 128
#define MODCHAINS_PATH "/modChains/"
#define IO_USER_DEF_MENUS 16
#define IO_UTILITY_MENUS 10
#define IO_MAX_MENUS IO_USER_DEF_MENUS+IO_UTILITY_MENUS
#define IO_INT32_MENU IO_USER_DEF_MENUS+1
#define IO_FLOAT_MENU IO_USER_DEF_MENUS+2
#define IO_BOOL_MENU IO_USER_DEF_MENUS+3
#define IO_STRING_MENU IO_USER_DEF_MENUS+4
#define IO_FILENAME_MENU IO_USER_DEF_MENUS+5
#define IO_FLOAT_STEP 0.01f